<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Features\SchoolClassManagement\AttendanceManagement\Queries\GetAttendanceReport\**" />
    <Compile Remove="Features\SchoolClassManagement\AttendanceManagement\Queries\GetAttendanceStatistics\**" />
    <EmbeddedResource Remove="Features\SchoolClassManagement\AttendanceManagement\Queries\GetAttendanceReport\**" />
    <EmbeddedResource Remove="Features\SchoolClassManagement\AttendanceManagement\Queries\GetAttendanceStatistics\**" />
    <None Remove="Features\SchoolClassManagement\AttendanceManagement\Queries\GetAttendanceReport\**" />
    <None Remove="Features\SchoolClassManagement\AttendanceManagement\Queries\GetAttendanceStatistics\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Auth\Mappings\" />
    <Folder Include="Features\SchoolClassManagement\ExamManagement\Queries\" />
    <Folder Include="Features\SchoolClassManagement\QuestionManagement\Commands\" />
    <Folder Include="Features\SchoolClassManagement\QuestionManagement\Queries\" />
    <Folder Include="Validators\" />
  </ItemGroup>


	<ItemGroup>
		<PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
		<PackageReference Include="Microsoft.AspNetCore.Authorization" Version="10.0.1" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.1" />
		<PackageReference Include="MongoDB.Driver" Version="3.5.2" />
		<PackageReference Include="MediatR" Version="14.0.0" />
	</ItemGroup>


	<ItemGroup>
    <ProjectReference Include="..\Contracts\Contracts.csproj" />
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

</Project>
